# yaml-language-server: $schema=./image.schema.json
schemaVersion: 3
profile: build

image:
  platform: linux/amd64

wolfi:
  baseImage: cgr.dev/chainguard/wolfi-base:latest
  repositories:
    main: https://apk.cgr.dev/chainguard
    extra: https://apk.cgr.dev/extra-packages

docker:
  cli: latest
  buildx: latest
  compose: latest
  socket: false

build:
  native:
    clang: latest
  python:
    - "3.12"
    - "3.13"
  java: "26"
  maven: "3.9"
  node: "24"
  npm: "12"
  rust:
    toolchain: nightly-2026-09-04
    components:
      - rust-src
      - rust-analyzer
      - rustfmt
      - clippy

playwright:
  version: "1.63.0"

utilities:
  curl: latest
  openssh-client: latest
  openssh-keygen: latest
  openssh-keyscan: latest
  unzip: latest
  zip: latest
  less: latest
  procps: latest
  findutils: latest
  kubectl: "1.37.0"
  yq: "4"
  helm: "4"
  oras: "1"
  mongosh: "2"
  mongodbDatabaseTools: "100"
  rsync: latest
  wget: latest
  nano: latest
  bind-tools: latest
  iproute2: latest
  iputils: latest
  netcat-openbsd: latest
