#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  compare.sh [options]

Options:
  --config FILE            Human-authored Wolfi YAML paired with the lock.
  --lock FILE              Wolfi lock used to locate its artifact root.
  --ubuntu-dir DIR         Fresh raw Ubuntu reports from wolfi/scan.sh.
  --ubuntu-policy-dir DIR  Separate Ubuntu header-policy report directory.
  --wolfi-dir DIR          Wolfi Trivy reports. Defaults to <artifact-root>/trivy-output.
  --output-dir DIR         Comparison output. Defaults to <artifact-root>/comparison.
  --suite-file FILE        scan-suite provenance generated by wolfi/scan.sh.
  --acceptance-file FILE   final-image gate result generated by wolfi/scan.sh.
  --native-tool-version-report FILE
                           mongosh APK/runtime report from wolfi/test-all.sh.
  --allow-unverified-scan-context
                           Compare ad-hoc reports without proving identical Trivy/DB/options.
  --skip-image-metrics     Compare reports without querying Docker.
  --basic-image-metrics    Skip compressed save/export and live-filesystem measurements.
  --full-image-metrics     Explicitly select the default full measurements.
  --require-image-metrics  Fail if any requested Docker metric is unavailable.
  -h, --help               Show help.

Historical artifacts/trivy-output is policy-adjusted and is never silently
treated as a raw or fair all-tools baseline. Run ./scripts/wolfi/scan.sh first.
USAGE
}

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_FILE="${WOLFI_BUILD_CONFIG:-${REPO_ROOT}/config/wolfi-build.yaml}"
LOCK_FILE="${WOLFI_LOCK_FILE:-${REPO_ROOT}/config/wolfi-build.lock.json}"
UBUNTU_DIR=""
UBUNTU_POLICY_DIR=""
WOLFI_DIR=""
OUTPUT_DIR=""
SUITE_FILE=""
ACCEPTANCE_FILE=""
NATIVE_TOOL_VERSION_REPORT=""
NATIVE_TOOL_VERSION_REPORT_EXPLICIT=false
METRIC_ARGS=(--full-image-metrics)
ALLOW_UNVERIFIED=false

while (($# > 0)); do
  case "$1" in
    --config|--lock)
      if (($# < 2)); then
        echo "ERROR: $1 requires a value." >&2
        usage >&2
        exit 1
      fi
      if [[ "$1" == --config ]]; then
        CONFIG_FILE="$2"
      else
        LOCK_FILE="$2"
      fi
      shift 2
      ;;
    --ubuntu-dir|--ubuntu-policy-dir|--suite-file|--acceptance-file|--native-tool-version-report)
      if (($# < 2)); then
        echo "ERROR: $1 requires a value." >&2
        usage >&2
        exit 1
      fi
      option="$1"
      case "${option}" in
        --ubuntu-dir) UBUNTU_DIR="$2" ;;
        --ubuntu-policy-dir) UBUNTU_POLICY_DIR="$2" ;;
        --suite-file) SUITE_FILE="$2" ;;
        --acceptance-file) ACCEPTANCE_FILE="$2" ;;
        --native-tool-version-report)
          NATIVE_TOOL_VERSION_REPORT="$2"
          NATIVE_TOOL_VERSION_REPORT_EXPLICIT=true
          ;;
      esac
      shift 2
      ;;
    --wolfi-dir)
      if (($# < 2)); then
        echo "ERROR: --wolfi-dir requires a value." >&2
        usage >&2
        exit 1
      fi
      WOLFI_DIR="$2"
      shift 2
      ;;
    --output-dir)
      if (($# < 2)); then
        echo "ERROR: --output-dir requires a value." >&2
        usage >&2
        exit 1
      fi
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --skip-image-metrics)
      METRIC_ARGS=(--skip-image-metrics)
      shift
      ;;
    --basic-image-metrics)
      METRIC_ARGS=()
      shift
      ;;
    --full-image-metrics)
      METRIC_ARGS=(--full-image-metrics)
      shift
      ;;
    --require-image-metrics)
      METRIC_ARGS+=(--require-image-metrics)
      shift
      ;;
    --allow-unverified-scan-context)
      ALLOW_UNVERIFIED=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

# shellcheck source=scripts/wolfi/lib.sh
source "${REPO_ROOT}/scripts/wolfi/lib.sh"
CONFIG_FILE="$(wolfi_abs_path "${REPO_ROOT}" "${CONFIG_FILE}")"
LOCK_FILE="$(wolfi_abs_path "${REPO_ROOT}" "${LOCK_FILE}")"
wolfi_verify_lock "${REPO_ROOT}" "${CONFIG_FILE}" "${LOCK_FILE}"

artifact_root="${REPO_ROOT}/artifacts/wolfi"
if [[ -z "${WOLFI_DIR}" || -z "${UBUNTU_DIR}" || -z "${UBUNTU_POLICY_DIR}" \
  || -z "${OUTPUT_DIR}" || -z "${SUITE_FILE}" ]] && [[ -f "${LOCK_FILE}" ]]; then
  if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: Required command not found: jq" >&2
    exit 1
  fi
  if locked_artifact_root="$(jq -er '.config.artifacts.root | select(type == "string" and length > 0)' "${LOCK_FILE}")"; then
    if [[ "${locked_artifact_root}" == /* ]]; then
      artifact_root="${locked_artifact_root}"
    else
      artifact_root="${REPO_ROOT}/${locked_artifact_root}"
    fi
  else
    echo "ERROR: Unable to read the Wolfi artifact root from lock:" >&2
    echo "  ${LOCK_FILE}" >&2
    exit 1
  fi
fi

if [[ -z "${WOLFI_DIR}" ]]; then
  WOLFI_DIR="${artifact_root}/trivy-output"
fi
if [[ -z "${UBUNTU_DIR}" ]]; then
  UBUNTU_DIR="${artifact_root}/ubuntu-trivy-output/raw"
fi
if [[ -z "${UBUNTU_POLICY_DIR}" ]]; then
  UBUNTU_POLICY_DIR="${artifact_root}/ubuntu-trivy-output/policy-header-packages"
fi
if [[ -z "${OUTPUT_DIR}" ]]; then
  OUTPUT_DIR="${artifact_root}/comparison"
fi
if [[ -z "${SUITE_FILE}" ]]; then
  SUITE_FILE="${artifact_root}/trivy-scan-suite.json"
fi
if [[ -z "${ACCEPTANCE_FILE}" ]]; then
  ACCEPTANCE_FILE="${WOLFI_DIR}/acceptance.json"
fi
if [[ -z "${NATIVE_TOOL_VERSION_REPORT}" ]]; then
  locked_platform="$(jq -er '.config.images.platform' "${LOCK_FILE}")"
  NATIVE_TOOL_VERSION_REPORT="${artifact_root}/${locked_platform//\//-}/reports/native-tool-versions.json"
fi
if [[ "${UBUNTU_DIR}" != /* ]]; then
  UBUNTU_DIR="${REPO_ROOT}/${UBUNTU_DIR}"
fi
if [[ "${WOLFI_DIR}" != /* ]]; then
  WOLFI_DIR="${REPO_ROOT}/${WOLFI_DIR}"
fi
if [[ "${UBUNTU_POLICY_DIR}" != /* ]]; then
  UBUNTU_POLICY_DIR="${REPO_ROOT}/${UBUNTU_POLICY_DIR}"
fi
if [[ "${OUTPUT_DIR}" != /* ]]; then
  OUTPUT_DIR="${REPO_ROOT}/${OUTPUT_DIR}"
fi
if [[ "${SUITE_FILE}" != /* ]]; then
  SUITE_FILE="${REPO_ROOT}/${SUITE_FILE}"
fi
if [[ "${ACCEPTANCE_FILE}" != /* ]]; then
  ACCEPTANCE_FILE="${REPO_ROOT}/${ACCEPTANCE_FILE}"
fi
if [[ "${NATIVE_TOOL_VERSION_REPORT}" != /* ]]; then
  NATIVE_TOOL_VERSION_REPORT="${REPO_ROOT}/${NATIVE_TOOL_VERSION_REPORT}"
fi

CONTEXT_ARGS=(
  --suite-metadata "${SUITE_FILE}"
  --acceptance-file "${ACCEPTANCE_FILE}"
  --ubuntu-policy-dir "${UBUNTU_POLICY_DIR}"
  --wolfi-lock "${LOCK_FILE}"
)
if [[ "${NATIVE_TOOL_VERSION_REPORT_EXPLICIT}" == true ]] \
  || jq -e '.config.toolchain | has("mongosh")' "${LOCK_FILE}" >/dev/null; then
  CONTEXT_ARGS+=(--native-tool-version-report "${NATIVE_TOOL_VERSION_REPORT}")
fi
if [[ "${ALLOW_UNVERIFIED}" == true ]]; then
  CONTEXT_ARGS+=(--allow-unverified-scan-context)
fi

exec python3 "${REPO_ROOT}/scripts/wolfi/compare-reports.py" \
  --ubuntu-dir "${UBUNTU_DIR}" \
  --wolfi-dir "${WOLFI_DIR}" \
  --output-dir "${OUTPUT_DIR}" \
  "${CONTEXT_ARGS[@]}" \
  "${METRIC_ARGS[@]}"
