#!/usr/bin/env python3
"""Compare Ubuntu and Wolfi Trivy reports without changing their source format."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import zlib
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Iterable


SEVERITIES = ("UNKNOWN", "LOW", "MEDIUM", "HIGH", "CRITICAL")
BLOCKING_SEVERITIES = ("CRITICAL", "HIGH")
RELEASE_GATE_POLICY = (
    "pristine Wolfi images must contain no CRITICAL or HIGH findings"
)
IMAGE_ID_PATTERN = re.compile(r"^sha256:[a-f0-9]{64}$")
DATABASE_TOOL_MARKERS = (
    "bsondump",
    "mongoexport",
    "mongofiles",
    "mongoimport",
    "mongorestore",
    "mongodump",
    "mongostat",
    "mongotop",
    "mongodb-database-tools",
)


def validate_output_directory_target(output_dir: Path) -> tuple[Path, str]:
    output_parent = output_dir.parent
    output_name = output_dir.name
    if not output_name:
        raise ValueError("comparison output directory must not be the filesystem root")

    output_parent.mkdir(parents=True, exist_ok=True)
    if output_dir.is_symlink() or (output_dir.exists() and not output_dir.is_dir()):
        raise ValueError(
            f"comparison output path must be a directory, not {output_dir}"
        )
    return output_parent, output_name


def quarantine_current_output_directory(output_dir: Path) -> Path | None:
    """Move an earlier result out of the canonical path before evaluation."""

    output_parent, output_name = validate_output_directory_target(output_dir)
    if not output_dir.exists():
        return None

    previous_dir = Path(
        tempfile.mkdtemp(prefix=f".{output_name}.previous-", dir=output_parent)
    )
    previous_dir.rmdir()
    output_dir.replace(previous_dir)
    print(
        f"Previous comparison quarantined as non-current: {previous_dir}",
        file=sys.stderr,
    )
    return previous_dir


def publish_complete_output_directory(
    output_dir: Path,
    writer: Callable[[Path], None],
    previous_dir: Path | None = None,
) -> None:
    """Stage a complete report set beside its empty canonical destination."""

    output_parent, output_name = validate_output_directory_target(output_dir)
    if output_dir.exists():
        raise RuntimeError(
            f"comparison output became current during evaluation: {output_dir}"
        )

    staging_dir = Path(
        tempfile.mkdtemp(prefix=f".{output_name}.staging-", dir=output_parent)
    )
    try:
        writer(staging_dir)
        if output_dir.exists():
            raise RuntimeError(
                f"comparison output became current during staging: {output_dir}"
            )
        staging_dir.replace(output_dir)
        if previous_dir is not None and previous_dir.exists():
            shutil.rmtree(previous_dir)
    finally:
        if staging_dir.exists():
            shutil.rmtree(staging_dir)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare vulnerability counts and image metrics for Ubuntu and Wolfi."
    )
    parser.add_argument("--ubuntu-dir", required=True, type=Path)
    parser.add_argument("--ubuntu-policy-dir", type=Path)
    parser.add_argument("--wolfi-dir", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--suite-metadata", type=Path)
    parser.add_argument(
        "--wolfi-lock",
        type=Path,
        help="Current frozen Wolfi lock used to validate suite identity and roles.",
    )
    parser.add_argument(
        "--acceptance-file",
        type=Path,
        help="Final-image acceptance result generated by scripts/wolfi/scan.sh.",
    )
    parser.add_argument("--native-tool-version-report", type=Path)
    parser.add_argument(
        "--allow-unverified-scan-context",
        action="store_true",
        help="Allow ad-hoc reports without matching Trivy scan metadata.",
    )
    parser.add_argument(
        "--skip-image-metrics",
        action="store_true",
        help="Do not query the local Docker image store.",
    )
    parser.add_argument(
        "--full-image-metrics",
        action="store_true",
        help="Also measure compressed docker-save and logical live-filesystem bytes.",
    )
    parser.add_argument(
        "--require-image-metrics",
        action="store_true",
        help="Fail when any requested Docker image metric is unavailable.",
    )
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    try:
        with path.open(encoding="utf-8") as input_file:
            value = json.load(input_file)
    except (OSError, json.JSONDecodeError) as error:
        raise SystemExit(f"ERROR: Unable to read {path}: {error}") from error
    if not isinstance(value, dict):
        raise SystemExit(f"ERROR: Expected a JSON object in {path}")
    return value


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as input_file:
            for chunk in iter(lambda: input_file.read(1024 * 1024), b""):
                digest.update(chunk)
    except OSError as error:
        raise SystemExit(f"ERROR: Unable to hash {path}: {error}") from error
    return digest.hexdigest()


def load_wolfi_lock_identity(path: Path) -> dict[str, Any]:
    resolved_path = path.resolve()
    if not resolved_path.is_file():
        raise SystemExit(f"ERROR: Current Wolfi lock not found: {resolved_path}")
    lock = read_json(resolved_path)
    images = lock.get("images")
    config = lock.get("config")
    config_images = config.get("images") if isinstance(config, dict) else None
    if lock.get("schemaVersion") != 1 or not isinstance(images, dict):
        raise SystemExit("ERROR: Current Wolfi lock has an invalid identity shape")
    if not isinstance(config_images, dict):
        raise SystemExit("ERROR: Current Wolfi lock has invalid image configuration")
    config_toolchain = config.get("toolchain")
    if not isinstance(config_toolchain, dict):
        raise SystemExit("ERROR: Current Wolfi lock has invalid toolchain configuration")
    platform = config_images.get("platform")
    if not isinstance(platform, str) or not platform:
        raise SystemExit("ERROR: Current Wolfi lock has an invalid platform")

    final_images: list[str] = []
    for role in ("dod", "vscode", "toolchain"):
        value = images.get(role)
        if not isinstance(value, dict):
            raise SystemExit(f"ERROR: Current Wolfi lock lacks image role: {role}")
        reference = value.get("reference")
        image_platform = value.get("platform")
        if not isinstance(reference, str) or not reference:
            raise SystemExit(f"ERROR: Current Wolfi lock has an invalid {role} image")
        if image_platform != platform:
            raise SystemExit(
                f"ERROR: Current Wolfi lock {role} image platform differs from config"
            )
        final_images.append(reference)
    if len(set(final_images)) != len(final_images):
        raise SystemExit("ERROR: Current Wolfi lock reuses a final image reference")

    toolchain_repository, separator, toolchain_tag = final_images[2].rpartition(":")
    if not separator or not toolchain_repository or not toolchain_tag:
        raise SystemExit("ERROR: Current Wolfi toolchain image lacks an explicit tag")
    probe_suffixes = {
        "helm": "probe-helm",
        "oras": "probe-oras",
        "mongosh": "probe-mongosh",
        "mongodbDatabaseTools": "probe-mongodb-database-tools",
    }
    configured_native_tools = [
        tool for tool in probe_suffixes if tool in config_toolchain
    ]
    probe_images = [f"{toolchain_repository}:{toolchain_tag}-core"]
    probe_images.extend(
        f"{toolchain_repository}:{toolchain_tag}-{probe_suffixes[tool]}"
        for tool in configured_native_tools
    )
    return {
        "path": str(resolved_path),
        "sha256": sha256_file(resolved_path),
        "platform": platform,
        "finalImages": final_images,
        "configuredNativeTools": configured_native_tools,
        "probeImages": probe_images,
    }


def validate_native_tool_probe_assessment(
    wolfi_suite: dict[str, Any],
    manifested_images: list[str],
    lock_identity: dict[str, Any] | None,
) -> bool:
    """Validate that a completeness claim covers every lock-required probe."""
    assessment = wolfi_suite.get("nativeToolProbeAssessment")
    if not isinstance(assessment, dict):
        if lock_identity is not None:
            raise SystemExit(
                "ERROR: Scan suite lacks the locked native-tool probe assessment"
            )
        return False

    locked_default = assessment.get("lockedDefaultEvaluation")
    complete = assessment.get("complete")
    if not isinstance(locked_default, bool) or not isinstance(complete, bool):
        raise SystemExit("ERROR: Scan-suite native-tool probe status is invalid")
    required_probes = assessment.get("requiredProbes")
    if not isinstance(required_probes, list):
        raise SystemExit("ERROR: Scan-suite required native-tool probes are invalid")

    tool_keys: list[str] = []
    probe_images: list[str] = []
    for probe in required_probes:
        if not isinstance(probe, dict) or set(probe) != {"toolKey", "image"}:
            raise SystemExit("ERROR: Scan-suite required native-tool probe is invalid")
        tool_key = probe.get("toolKey")
        image = probe.get("image")
        if (
            not isinstance(tool_key, str)
            or not tool_key
            or not isinstance(image, str)
            or not image
        ):
            raise SystemExit("ERROR: Scan-suite required native-tool probe is invalid")
        tool_keys.append(tool_key)
        probe_images.append(image)
    if len(set(tool_keys)) != len(tool_keys) or len(set(probe_images)) != len(
        probe_images
    ):
        raise SystemExit("ERROR: Scan-suite required native-tool probes are duplicated")

    suite_probe_images = wolfi_suite.get("probeImages")
    if not isinstance(suite_probe_images, list) or suite_probe_images != probe_images:
        raise SystemExit(
            "ERROR: Scan-suite native-tool probe manifest differs from its assessment"
        )
    if any(image not in manifested_images for image in probe_images):
        raise SystemExit(
            "ERROR: Scan-suite required native-tool probe is absent from raw reports"
        )

    if lock_identity is not None:
        expected_tool_keys = ["core", *lock_identity["configuredNativeTools"]]
        if tool_keys != expected_tool_keys or probe_images != lock_identity["probeImages"]:
            raise SystemExit(
                "ERROR: Scan-suite native-tool probe manifest differs from the "
                "current lock"
            )
        if locked_default is not True or complete is not True:
            raise SystemExit(
                "ERROR: Locked native-tool probe assessment is not complete"
            )
        return True

    # Without the lock, a suite cannot prove which optional tools were configured.
    # It may carry partial custom-scan diagnostics, but not a verified completeness
    # claim used for an equivalent all-tools comparison.
    return False


def load_scan_metadata(report_dir: Path) -> dict[str, Any] | None:
    metadata_path = report_dir / "scan-metadata.json"
    if not metadata_path.is_file():
        return None
    metadata = read_json(metadata_path)
    metadata["_path"] = str(metadata_path)
    return metadata


def metadata_report_paths(
    report_dir: Path, metadata: dict[str, Any] | None
) -> list[Path]:
    if metadata is None:
        return sorted(report_dir.glob("*.vulnerabilities.json"))
    images = metadata.get("images")
    if (
        not isinstance(images, list)
        or not images
        or any(not isinstance(image, str) or not image for image in images)
        or len(set(images)) != len(images)
    ):
        raise SystemExit(
            f"ERROR: Scan metadata has an invalid image manifest: {metadata.get('_path')}"
        )
    reports = metadata.get("reports")
    if not isinstance(reports, list) or not reports:
        raise SystemExit(
            f"ERROR: Scan metadata has no report manifest: {metadata.get('_path')}"
        )
    report_paths: list[Path] = []
    report_images: list[str] = []
    manifested_names: set[str] = set()
    report_hashes_present: list[bool] = []
    for item in reports:
        if not isinstance(item, dict):
            raise SystemExit("ERROR: Invalid report entry in scan metadata")
        image = item.get("image")
        if not isinstance(image, str) or not image:
            raise SystemExit("ERROR: Invalid report image in scan metadata")
        report_images.append(image)
        for field in ("vulnerabilities", "sbom"):
            relative = item.get(field)
            if (
                not isinstance(relative, str)
                or not relative
                or Path(relative).name != relative
                or relative in manifested_names
            ):
                raise SystemExit(
                    f"ERROR: Unsafe or duplicate report path in scan metadata: {relative!r}"
                )
            manifested_names.add(relative)
            manifested_path = report_dir / relative
            if not manifested_path.is_file():
                raise SystemExit(
                    f"ERROR: Manifested Trivy report is missing: {manifested_path}"
                )
            hash_field = f"{field}Sha256"
            expected_hash = item.get(hash_field)
            if expected_hash is None:
                report_hashes_present.append(False)
            elif (
                not isinstance(expected_hash, str)
                or re.fullmatch(r"[a-f0-9]{64}", expected_hash) is None
            ):
                raise SystemExit(
                    f"ERROR: Invalid {field} hash in scan metadata: {expected_hash!r}"
                )
            else:
                report_hashes_present.append(True)
                if sha256_file(manifested_path) != expected_hash:
                    raise SystemExit(
                        f"ERROR: Manifested Trivy report hash differs: {manifested_path}"
                    )
        report_path = report_dir / item["vulnerabilities"]
        report_paths.append(report_path)

    if report_images != images:
        raise SystemExit(
            f"ERROR: Scan image and report manifests differ: {metadata.get('_path')}"
        )

    identities = metadata.get("imageIdentities")
    identity_by_image: dict[str, dict[str, Any]] = {}
    if identities is not None:
        if not isinstance(identities, list):
            raise SystemExit("ERROR: Invalid image identity manifest in scan metadata")
        identity_images: list[str] = []
        scanner_platform = (metadata.get("scannerOptions") or {}).get("platform")
        for identity in identities:
            if not isinstance(identity, dict):
                raise SystemExit("ERROR: Invalid image identity in scan metadata")
            reference = identity.get("reference")
            image_id = identity.get("imageId")
            platform = identity.get("platform")
            if (
                not isinstance(reference, str)
                or not reference
                or not isinstance(image_id, str)
                or IMAGE_ID_PATTERN.fullmatch(image_id) is None
                or not isinstance(platform, str)
                or not platform
                or (scanner_platform and platform != scanner_platform)
            ):
                raise SystemExit("ERROR: Invalid image identity in scan metadata")
            identity_images.append(reference)
            identity_by_image[reference] = identity
        if identity_images != images or len(identity_by_image) != len(images):
            raise SystemExit(
                f"ERROR: Image identity manifest differs from scan images: {metadata.get('_path')}"
            )
    metadata["_identityByImage"] = identity_by_image
    metadata["_imageIdentityVerified"] = bool(identity_by_image)
    metadata["_reportHashesVerified"] = bool(report_hashes_present) and all(
        report_hashes_present
    )
    return report_paths


def comparable_scanner_options(metadata: dict[str, Any]) -> dict[str, Any]:
    options = metadata.get("scannerOptions")
    if not isinstance(options, dict):
        raise SystemExit(
            f"ERROR: Invalid scanner options in {metadata.get('_path', 'scan metadata')}"
        )
    return {key: value for key, value in options.items() if key != "ignorePolicy"}


def comparable_image_identities(metadata: dict[str, Any]) -> dict[str, tuple[str, str]]:
    return {
        reference: (str(identity.get("imageId") or ""), str(identity.get("platform") or ""))
        for reference, identity in (metadata.get("_identityByImage") or {}).items()
    }


def verify_scan_context(
    ubuntu_metadata: dict[str, Any] | None,
    wolfi_metadata: dict[str, Any] | None,
    policy_metadata: dict[str, Any] | None,
    allow_unverified: bool,
) -> dict[str, Any]:
    missing = [
        label
        for label, value in (
            ("Ubuntu raw", ubuntu_metadata),
            ("Wolfi raw", wolfi_metadata),
        )
        if value is None
    ]
    if missing:
        reason = f"Missing scan-metadata.json for: {', '.join(missing)}"
        if not allow_unverified:
            raise SystemExit(
                f"ERROR: {reason}. Run scripts/wolfi/scan.sh or pass "
                "--allow-unverified-scan-context for explicitly ad-hoc reports."
            )
        return {"verified": False, "reason": reason}

    assert ubuntu_metadata is not None and wolfi_metadata is not None
    contexts = (ubuntu_metadata, wolfi_metadata)
    for label, metadata in zip(("Ubuntu raw", "Wolfi raw"), contexts):
        ignore_policy = (metadata.get("scannerOptions") or {}).get("ignorePolicy") or {}
        if ignore_policy.get("applied") is not False:
            raise SystemExit(f"ERROR: {label} scan is not raw")

    missing_identities = [
        label
        for label, metadata in zip(("Ubuntu raw", "Wolfi raw"), contexts)
        if metadata.get("_imageIdentityVerified") is not True
    ]
    missing_hashes = [
        label
        for label, metadata in zip(("Ubuntu raw", "Wolfi raw"), contexts)
        if metadata.get("_reportHashesVerified") is not True
    ]
    if missing_identities or missing_hashes:
        details = []
        if missing_identities:
            details.append("image identities for " + ", ".join(missing_identities))
        if missing_hashes:
            details.append("report hashes for " + ", ".join(missing_hashes))
        reason = "Missing immutable scan provenance: " + "; ".join(details)
        if not allow_unverified:
            raise SystemExit(f"ERROR: {reason}")
        return {"verified": False, "reason": reason}

    mismatch_fields = []
    if ubuntu_metadata.get("trivy", {}).get("Version") != wolfi_metadata.get(
        "trivy", {}
    ).get("Version"):
        mismatch_fields.append("Trivy version")
    if ubuntu_metadata.get("databaseIdentity") != wolfi_metadata.get(
        "databaseIdentity"
    ):
        mismatch_fields.append("database snapshot")
    if comparable_scanner_options(ubuntu_metadata) != comparable_scanner_options(
        wolfi_metadata
    ):
        mismatch_fields.append("scanner options")
    if mismatch_fields:
        reason = "Raw scan context differs: " + ", ".join(mismatch_fields)
        if not allow_unverified:
            raise SystemExit(f"ERROR: {reason}")
        return {"verified": False, "reason": reason}

    if policy_metadata is not None:
        if policy_metadata.get("_imageIdentityVerified") is not True or policy_metadata.get(
            "_reportHashesVerified"
        ) is not True:
            raise SystemExit(
                "ERROR: Ubuntu policy view lacks immutable image/report provenance"
            )
        ignore_policy = (policy_metadata.get("scannerOptions") or {}).get(
            "ignorePolicy"
        ) or {}
        if ignore_policy.get("applied") is not True:
            raise SystemExit("ERROR: Ubuntu policy view did not apply an ignore policy")
        if policy_metadata.get("trivy", {}).get("Version") != ubuntu_metadata.get(
            "trivy", {}
        ).get("Version") or policy_metadata.get("databaseIdentity") != ubuntu_metadata.get(
            "databaseIdentity"
        ):
            raise SystemExit("ERROR: Ubuntu policy view used a different Trivy/DB snapshot")
        if comparable_scanner_options(policy_metadata) != comparable_scanner_options(
            ubuntu_metadata
        ):
            raise SystemExit("ERROR: Ubuntu policy view used different scanner options")
        if policy_metadata.get("images") != ubuntu_metadata.get("images"):
            raise SystemExit("ERROR: Ubuntu policy view used a different image manifest")
        if comparable_image_identities(policy_metadata) != comparable_image_identities(
            ubuntu_metadata
        ):
            raise SystemExit("ERROR: Ubuntu policy view used different image identities")

    return {
        "verified": True,
        "reason": "Ubuntu and Wolfi raw scans share one frozen Trivy/DB/options context.",
        "trivyVersion": ubuntu_metadata.get("trivy", {}).get("Version"),
        "databaseIdentity": ubuntu_metadata.get("databaseIdentity"),
        "scannerOptions": comparable_scanner_options(ubuntu_metadata),
        "ubuntuPolicyViewVerified": policy_metadata is not None,
        "vsixArchiveExcluded": "/home/vscode/vscode-extensions.tar.gz"
        in (comparable_scanner_options(ubuntu_metadata).get("skipFiles") or []),
    }


def normalize_severity(value: object) -> str:
    severity = str(value or "UNKNOWN").upper()
    return severity if severity in SEVERITIES else "UNKNOWN"


def classify_native_tool(finding: dict[str, Any]) -> str:
    haystack = " ".join(
        str(finding.get(key) or "").lower()
        for key in ("target", "packageName", "packagePath")
    )
    if "mongosh" in haystack:
        return "mongosh"
    if any(marker in haystack for marker in DATABASE_TOOL_MARKERS):
        return "mongodb-database-tools"

    tokens = set(re.split(r"[^a-z0-9]+", haystack))
    if "helm" in tokens:
        return "helm"
    if "oras" in tokens:
        return "oras"
    return "base-or-other"


def collect_findings(report: dict[str, Any]) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    results = report.get("Results")
    if not isinstance(results, list):
        raise SystemExit("ERROR: Trivy report has an invalid Results array")
    for result in results:
        if not isinstance(result, dict):
            raise SystemExit("ERROR: Trivy report has an invalid result entry")
        vulnerabilities = result.get("Vulnerabilities") or []
        if not isinstance(vulnerabilities, list):
            raise SystemExit("ERROR: Trivy report has an invalid vulnerability list")
        for vulnerability in vulnerabilities:
            if not isinstance(vulnerability, dict):
                raise SystemExit("ERROR: Trivy report has an invalid vulnerability entry")
            layer = vulnerability.get("Layer") or {}
            layer_digest = str(layer.get("Digest") or "") if isinstance(layer, dict) else ""
            finding = {
                "vulnerabilityId": str(vulnerability.get("VulnerabilityID") or ""),
                "severity": normalize_severity(vulnerability.get("Severity")),
                "fixAvailable": bool(str(vulnerability.get("FixedVersion") or "")),
                "target": str(result.get("Target") or ""),
                "packageClass": str(result.get("Class") or ""),
                "packageType": str(result.get("Type") or ""),
                "packageName": str(vulnerability.get("PkgName") or ""),
                "packagePath": str(vulnerability.get("PkgPath") or ""),
                "installedVersion": str(vulnerability.get("InstalledVersion") or ""),
                "fixedVersion": str(vulnerability.get("FixedVersion") or ""),
                "layerDigest": layer_digest,
            }
            finding["nativeTool"] = classify_native_tool(finding)
            findings.append(finding)
    return findings


def count_components(components: object) -> int:
    if not isinstance(components, list):
        return 0
    total = 0
    for component in components:
        if not isinstance(component, dict):
            continue
        total += 1 + count_components(component.get("components"))
    return total


def sbom_component_count(report_path: Path) -> int | None:
    suffix = ".vulnerabilities.json"
    if not report_path.name.endswith(suffix):
        return None
    sbom_path = report_path.with_name(
        f"{report_path.name.removesuffix(suffix)}.sbom.cdx.json"
    )
    if not sbom_path.is_file():
        return None
    sbom = read_json(sbom_path)
    components = sbom.get("components")
    if sbom.get("bomFormat") != "CycloneDX" or not isinstance(components, list):
        raise SystemExit(f"ERROR: Invalid CycloneDX SBOM: {sbom_path}")
    return count_components(components)


def count_payload(findings: Iterable[dict[str, Any]]) -> dict[str, Any]:
    finding_list = list(findings)
    occurrences = Counter(finding["severity"] for finding in finding_list)
    unique_by_severity: dict[str, set[str]] = {
        severity: set() for severity in SEVERITIES
    }
    fix_occurrences = {
        "available": Counter(),
        "unavailable": Counter(),
    }
    fix_unique: dict[str, dict[str, set[str]]] = {
        availability: {severity: set() for severity in SEVERITIES}
        for availability in fix_occurrences
    }

    for finding in finding_list:
        severity = finding["severity"]
        vulnerability_id = finding["vulnerabilityId"]
        availability = "available" if finding["fixAvailable"] else "unavailable"
        fix_occurrences[availability][severity] += 1
        if vulnerability_id:
            unique_by_severity[severity].add(vulnerability_id)
            fix_unique[availability][severity].add(vulnerability_id)

    unique_all = set().union(*unique_by_severity.values())
    payload: dict[str, Any] = {
        "occurrences": {
            **{severity: occurrences[severity] for severity in SEVERITIES},
            "TOTAL": len(finding_list),
        },
        "uniqueCves": {
            **{
                severity: len(unique_by_severity[severity])
                for severity in SEVERITIES
            },
            "TOTAL": len(unique_all),
        },
        "fixAvailability": {},
    }
    for availability in ("available", "unavailable"):
        availability_unique = set().union(*fix_unique[availability].values())
        payload["fixAvailability"][availability] = {
            "occurrences": {
                **{
                    severity: fix_occurrences[availability][severity]
                    for severity in SEVERITIES
                },
                "TOTAL": sum(fix_occurrences[availability].values()),
            },
            "uniqueCves": {
                **{
                    severity: len(fix_unique[availability][severity])
                    for severity in SEVERITIES
                },
                "TOTAL": len(availability_unique),
            },
        }
    return payload


def contribution_payload(
    findings: Iterable[dict[str, Any]], keys: tuple[str, ...]
) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, ...], list[dict[str, Any]]] = defaultdict(list)
    for finding in findings:
        grouped[tuple(str(finding[key]) for key in keys)].append(finding)

    contributions = []
    for group_key, grouped_findings in grouped.items():
        item = {key: value for key, value in zip(keys, group_key)}
        item["counts"] = count_payload(grouped_findings)
        item["vulnerabilityIds"] = sorted(
            {
                finding["vulnerabilityId"]
                for finding in grouped_findings
                if finding["vulnerabilityId"]
            }
        )
        contributions.append(item)
    return sorted(
        contributions,
        key=lambda item: (
            -item["counts"]["occurrences"]["TOTAL"],
            *(item[key].casefold() for key in keys),
        ),
    )


def load_family(name: str, report_dir: Path) -> dict[str, Any]:
    if not report_dir.is_dir():
        raise SystemExit(f"ERROR: Trivy report directory not found: {report_dir}")
    scan_metadata = load_scan_metadata(report_dir)
    report_paths = metadata_report_paths(report_dir, scan_metadata)
    if not report_paths:
        raise SystemExit(f"ERROR: No vulnerability JSON reports found in {report_dir}")

    images = []
    family_findings: list[dict[str, Any]] = []
    manifested_reports = {
        item["vulnerabilities"]: item
        for item in ((scan_metadata or {}).get("reports") or [])
    }
    identity_by_image = (scan_metadata or {}).get("_identityByImage") or {}
    for report_path in report_paths:
        report = read_json(report_path)
        manifested = manifested_reports.get(report_path.name)
        expected_image = manifested.get("image") if manifested else None
        report_image = report.get("ArtifactName")
        if expected_image is not None and report_image != expected_image:
            raise SystemExit(
                f"ERROR: Trivy report image does not match its manifest: {report_path}"
            )
        scanned_identity = identity_by_image.get(str(report_image))
        if scanned_identity is not None:
            report_image_id = (report.get("Metadata") or {}).get("ImageID")
            if report_image_id != scanned_identity.get("imageId"):
                raise SystemExit(
                    f"ERROR: Trivy report image ID does not match scan provenance: {report_path}"
                )
        findings = collect_findings(report)
        family_findings.extend(findings)
        images.append(
            {
                "name": str(report.get("ArtifactName") or report_path.name),
                "scannedImageIdentity": scanned_identity,
                "report": str(report_path),
                "sbomComponents": sbom_component_count(report_path),
                "counts": count_payload(findings),
                "nativeTools": contribution_payload(findings, ("nativeTool",)),
                "vulnerabilityLayers": contribution_payload(findings, ("layerDigest",)),
                "packages": contribution_payload(
                    findings,
                    (
                        "nativeTool",
                        "target",
                        "packageClass",
                        "packageType",
                        "packageName",
                        "packagePath",
                        "installedVersion",
                        "fixedVersion",
                        "layerDigest",
                    ),
                ),
                "_findings": findings,
            }
        )

    return {
        "name": name,
        "reportDirectory": str(report_dir),
        "scanMetadata": scan_metadata,
        "counts": count_payload(family_findings),
        "nativeTools": contribution_payload(family_findings, ("nativeTool",)),
        "images": images,
        "_findings": family_findings,
    }


def parse_human_size(value: str) -> int | None:
    match = re.fullmatch(r"\s*([0-9]+(?:\.[0-9]+)?)\s*([kmgtp]?i?b)\s*", value.lower())
    if not match:
        return None
    number = float(match.group(1))
    unit = match.group(2)
    decimal_units = {"b": 1, "kb": 1000, "mb": 1000**2, "gb": 1000**3, "tb": 1000**4, "pb": 1000**5}
    binary_units = {"kib": 1024, "mib": 1024**2, "gib": 1024**3, "tib": 1024**4, "pib": 1024**5}
    multiplier = decimal_units.get(unit, binary_units.get(unit))
    return round(number * multiplier) if multiplier is not None else None


def command_error(result: subprocess.CompletedProcess[str]) -> str:
    return (result.stderr or result.stdout or "command failed").strip().replace("\n", " ")


def measure_compressed_save(image: str) -> tuple[int | None, str]:
    with tempfile.TemporaryFile() as stderr_file:
        process = subprocess.Popen(
            ["docker", "image", "save", image],
            stdout=subprocess.PIPE,
            stderr=stderr_file,
        )
        assert process.stdout is not None
        compressor = zlib.compressobj(level=6, wbits=31)
        compressed_bytes = 0
        for chunk in iter(lambda: process.stdout.read(1024 * 1024), b""):
            compressed_bytes += len(compressor.compress(chunk))
        compressed_bytes += len(compressor.flush())
        return_code = process.wait()
        stderr_file.seek(0)
        error = stderr_file.read().decode(errors="replace").strip().replace("\n", " ")
    if return_code != 0:
        return None, error or "docker image save failed"
    return compressed_bytes, ""


class CompressCountingReader:
    """Compress every byte consumed by tarfile while preserving the stream."""

    def __init__(self, stream: Any) -> None:
        self.stream = stream
        self.compressor = zlib.compressobj(level=6, wbits=31)
        self.compressed_bytes = 0
        self.finished = False

    def read(self, size: int = -1) -> bytes:
        data = self.stream.read(size)
        if data:
            self.compressed_bytes += len(self.compressor.compress(data))
        elif not self.finished:
            self.compressed_bytes += len(self.compressor.flush())
            self.finished = True
        return data

    def drain(self) -> None:
        while self.read(1024 * 1024):
            pass


def measure_export(image: str) -> tuple[int | None, int | None, str]:
    create_result = subprocess.run(
        ["docker", "container", "create", "--entrypoint", "/bin/true", image],
        check=False,
        capture_output=True,
        text=True,
    )
    if create_result.returncode != 0:
        return None, None, command_error(create_result)
    container_id = create_result.stdout.strip()
    try:
        with tempfile.TemporaryFile() as stderr_file:
            process = subprocess.Popen(
                ["docker", "container", "export", container_id],
                stdout=subprocess.PIPE,
                stderr=stderr_file,
            )
            assert process.stdout is not None
            logical_bytes = 0
            reader = CompressCountingReader(process.stdout)
            try:
                with tarfile.open(fileobj=reader, mode="r|*") as archive:
                    for member in archive:
                        if member.isfile():
                            logical_bytes += member.size
            except tarfile.TarError as error:
                process.kill()
                process.wait()
                return None, None, f"unable to read docker export: {error}"
            reader.drain()
            return_code = process.wait()
            stderr_file.seek(0)
            error = stderr_file.read().decode(errors="replace").strip().replace("\n", " ")
        if return_code != 0:
            return None, None, error or "docker container export failed"
        return logical_bytes, reader.compressed_bytes, ""
    finally:
        subprocess.run(
            ["docker", "container", "rm", container_id],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )


def measure_package_count(image: str) -> tuple[int | None, str, str]:
    script = """
if command -v apk >/dev/null 2>&1; then
  printf 'apk\\t'
  apk info | wc -l
elif command -v dpkg-query >/dev/null 2>&1; then
  printf 'dpkg\\t'
  dpkg-query -W -f='${db:Status-Abbrev}\\n' \
    | awk 'substr($1, 1, 2) == "ii" { count++ } END { print count + 0 }'
else
  exit 44
fi
"""
    result = subprocess.run(
        [
            "docker",
            "container",
            "run",
            "--rm",
            "--network=none",
            "--entrypoint",
            "/bin/sh",
            image,
            "-c",
            script,
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None, "", command_error(result)
    try:
        package_manager, count = result.stdout.strip().split("\t", 1)
        return int(count), package_manager, ""
    except (ValueError, TypeError) as error:
        return None, "", f"unable to parse installed package count: {error}"


def collect_image_metrics(image: str, full: bool) -> dict[str, Any]:
    metrics: dict[str, Any] = {
        "available": False,
        "imageId": "",
        "platform": "",
        "imageSizeBytes": None,
        "layerCount": None,
        "rootfsLayerDigests": [],
        "largestHistoryLayerBytes": None,
        "historyLayers": [],
        "packageManager": "",
        "installedPackageCount": None,
        "compressedSaveBytes": None,
        "compressedExportBytes": None,
        "liveFilesystemBytes": None,
        "errors": [],
    }
    inspect_result = subprocess.run(
        ["docker", "image", "inspect", image],
        check=False,
        capture_output=True,
        text=True,
    )
    if inspect_result.returncode != 0:
        metrics["errors"].append(command_error(inspect_result))
        return metrics
    try:
        inspect_values = json.loads(inspect_result.stdout)
        inspect_value = inspect_values[0]
        image_id = str(inspect_value.get("Id") or "")
        if IMAGE_ID_PATTERN.fullmatch(image_id) is None:
            raise ValueError("invalid Docker image ID")
        metrics["imageId"] = image_id
        metrics["imageSizeBytes"] = int(inspect_value.get("Size"))
        rootfs = inspect_value.get("RootFS") or {}
        metrics["rootfsLayerDigests"] = list(rootfs.get("Layers") or [])
        metrics["layerCount"] = len(metrics["rootfsLayerDigests"])
        os_name = str(inspect_value.get("Os") or "")
        architecture = str(inspect_value.get("Architecture") or "")
        metrics["platform"] = f"{os_name}/{architecture}".strip("/")
        metrics["available"] = True
    except (IndexError, KeyError, TypeError, ValueError, json.JSONDecodeError) as error:
        metrics["errors"].append(f"unable to parse docker image inspect output: {error}")
        return metrics

    # Use the immutable ID captured above for every subsequent measurement so a
    # mutable tag cannot combine one scanned image with another image's metrics.
    metric_image = metrics["imageId"]
    history_result = subprocess.run(
        [
            "docker",
            "image",
            "history",
            "--no-trunc",
            "--format",
            "{{json .}}",
            metric_image,
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    if history_result.returncode == 0:
        history_sizes = []
        for index, line in enumerate(history_result.stdout.splitlines()):
            try:
                history_item = json.loads(line)
            except json.JSONDecodeError as error:
                metrics["errors"].append(f"unable to parse docker history row: {error}")
                continue
            size = parse_human_size(str(history_item.get("Size") or ""))
            if size is not None:
                history_sizes.append(size)
            metrics["historyLayers"].append(
                {
                    "index": index,
                    "id": str(history_item.get("ID") or ""),
                    "rootfsDigest": "",
                    "sizeBytes": size,
                    "createdBy": str(history_item.get("CreatedBy") or ""),
                    "comment": str(history_item.get("Comment") or ""),
                }
            )
        metrics["largestHistoryLayerBytes"] = max(history_sizes, default=0)
        filesystem_history = [
            layer
            for layer in reversed(metrics["historyLayers"])
            if isinstance(layer["sizeBytes"], int) and layer["sizeBytes"] > 0
        ]
        if len(filesystem_history) == len(metrics["rootfsLayerDigests"]):
            for layer, digest in zip(
                filesystem_history, metrics["rootfsLayerDigests"]
            ):
                layer["rootfsDigest"] = digest
        else:
            metrics["errors"].append(
                "could not align rounded docker-history entries to RootFS digests"
            )
    else:
        metrics["errors"].append(command_error(history_result))

    package_count, package_manager, package_error = measure_package_count(metric_image)
    metrics["installedPackageCount"] = package_count
    metrics["packageManager"] = package_manager
    if package_error:
        metrics["errors"].append(package_error)

    if full:
        compressed_size, compressed_error = measure_compressed_save(metric_image)
        metrics["compressedSaveBytes"] = compressed_size
        if compressed_error:
            metrics["errors"].append(compressed_error)
        live_size, compressed_export_size, live_error = measure_export(metric_image)
        metrics["liveFilesystemBytes"] = live_size
        metrics["compressedExportBytes"] = compressed_export_size
        if live_error:
            metrics["errors"].append(live_error)
    return metrics


def subtract_optional(left: object, right: object) -> int | None:
    if isinstance(left, int) and isinstance(right, int):
        return left - right
    return None


def find_image(family: dict[str, Any], name: str) -> dict[str, Any] | None:
    return next((image for image in family["images"] if image["name"] == name), None)


def metric_deltas(image: dict[str, Any], baseline: dict[str, Any]) -> dict[str, Any]:
    image_metrics = image["imageMetrics"]
    baseline_metrics = baseline["imageMetrics"]
    return {
        key: subtract_optional(image_metrics.get(key), baseline_metrics.get(key))
        for key in (
            "imageSizeBytes",
            "compressedSaveBytes",
            "compressedExportBytes",
            "liveFilesystemBytes",
            "installedPackageCount",
            "layerCount",
        )
    }


def vulnerability_deltas(
    image: dict[str, Any], baseline: dict[str, Any]
) -> dict[str, dict[str, int]]:
    return {
        category: {
            severity: image["counts"][category][severity]
            - baseline["counts"][category][severity]
            for severity in (*SEVERITIES, "TOTAL")
        }
        for category in ("occurrences", "uniqueCves")
    }


def build_probe_contributions(
    wolfi: dict[str, Any], suite: dict[str, Any] | None
) -> list[dict[str, Any]]:
    core = next(
        (image for image in wolfi["images"] if image["name"].endswith("-core")),
        None,
    )
    if core is None:
        return []

    configured_final = ""
    if suite is not None:
        configured_final = str(
            (((suite.get("wolfi") or {}).get("boundaries") or {}).get("toolchain"))
            or ""
        )
    variants = (
        ("helm", "-probe-helm"),
        ("oras", "-probe-oras"),
        ("mongosh", "-probe-mongosh"),
        ("mongodb-database-tools", "-probe-mongodb-database-tools"),
    )
    contributions: list[dict[str, Any]] = []
    for native_tool, suffix in variants:
        probe = next(
            (image for image in wolfi["images"] if image["name"].endswith(suffix)),
            None,
        )
        if probe is None:
            continue
        contributions.append(
            {
                "nativeTool": native_tool,
                "baselineImage": core["name"],
                "image": probe["name"],
                "metricDeltas": metric_deltas(probe, core),
                "vulnerabilityDeltas": vulnerability_deltas(probe, core),
            }
        )

    final = find_image(wolfi, configured_final) if configured_final else None
    if final is None:
        final = next(
            (
                image
                for image in wolfi["images"]
                if "wolfi-base-toolchain" in image["name"]
                and "-probe-" not in image["name"]
                and not image["name"].endswith("-core")
            ),
            None,
        )
    if final is not None:
        contributions.append(
            {
                "nativeTool": "all-enabled-native-tools",
                "baselineImage": core["name"],
                "image": final["name"],
                "metricDeltas": metric_deltas(final, core),
                "vulnerabilityDeltas": vulnerability_deltas(final, core),
            }
        )
    return contributions


def build_boundary_comparisons(
    ubuntu: dict[str, Any],
    wolfi: dict[str, Any],
    suite: dict[str, Any] | None,
) -> list[dict[str, Any]]:
    if suite is None:
        return [
            {
                "boundary": boundary,
                "comparable": False,
                "reason": "No scan-suite provenance identifies equivalent image roles.",
                "ubuntuImage": "",
                "wolfiImage": "",
            }
            for boundary in ("dod", "vscode", "toolchain-all-tools")
        ]

    ubuntu_data = suite.get("ubuntu") or {}
    wolfi_data = suite.get("wolfi") or {}
    ubuntu_boundaries = ubuntu_data.get("boundaries") or {}
    wolfi_boundaries = wolfi_data.get("boundaries") or {}
    all_tools = ubuntu_data.get("allToolsComparison") or {}
    specs = (
        (
            "dod",
            str(ubuntu_boundaries.get("dod") or ""),
            str(wolfi_boundaries.get("dod") or ""),
            True,
            "Equivalent Docker-outside-of-Docker boundary.",
        ),
        (
            "vscode",
            str(ubuntu_boundaries.get("vscode") or ""),
            str(wolfi_boundaries.get("vscode") or ""),
            True,
            "Equivalent VS Code Server and unexpanded extension-archive boundary.",
        ),
        (
            "toolchain-all-tools",
            str(all_tools.get("image") or ""),
            str(wolfi_boundaries.get("toolchain") or ""),
            all_tools.get("equivalent") is True,
            str(all_tools.get("reason") or "All-tools equivalence was not established."),
        ),
    )
    comparisons: list[dict[str, Any]] = []
    for boundary, ubuntu_name, wolfi_name, equivalent, reason in specs:
        ubuntu_image = find_image(ubuntu, ubuntu_name)
        wolfi_image = find_image(wolfi, wolfi_name)
        comparable = bool(equivalent and ubuntu_image is not None and wolfi_image is not None)
        item: dict[str, Any] = {
            "boundary": boundary,
            "comparable": comparable,
            "reason": reason
            if comparable
            else (
                reason
                if not equivalent
                else "One or both manifested boundary images are absent from the reports."
            ),
            "ubuntuImage": ubuntu_name,
            "wolfiImage": wolfi_name,
        }
        if comparable:
            assert ubuntu_image is not None and wolfi_image is not None
            item["metricDeltasWolfiMinusUbuntu"] = metric_deltas(
                wolfi_image, ubuntu_image
            )
            item["vulnerabilityDeltasWolfiMinusUbuntu"] = vulnerability_deltas(
                wolfi_image, ubuntu_image
            )
        comparisons.append(item)
    return comparisons


def gate_count_map(value: object, label: str) -> dict[str, int]:
    if not isinstance(value, dict):
        raise SystemExit(f"ERROR: Acceptance result has invalid {label}")
    counts: dict[str, int] = {}
    for severity in BLOCKING_SEVERITIES:
        count = value.get(severity)
        if not isinstance(count, int) or isinstance(count, bool) or count < 0:
            raise SystemExit(
                f"ERROR: Acceptance result has invalid {label}.{severity}"
            )
        counts[severity] = count
    return counts


def observed_gate_counts(images: list[dict[str, Any]]) -> tuple[dict[str, int], dict[str, int]]:
    occurrences = {
        severity: sum(image["counts"]["occurrences"][severity] for image in images)
        for severity in BLOCKING_SEVERITIES
    }
    unique_cves = {
        severity: len(
            {
                finding["vulnerabilityId"]
                for image in images
                for finding in image["_findings"]
                if finding["severity"] == severity and finding["vulnerabilityId"]
            }
        )
        for severity in BLOCKING_SEVERITIES
    }
    return occurrences, unique_cves


def build_release_gate(
    wolfi: dict[str, Any],
    suite: dict[str, Any] | None,
    scan_context: dict[str, Any],
    acceptance: dict[str, Any] | None,
    acceptance_path: Path | None,
) -> dict[str, Any]:
    final_names: list[str] = []
    if suite is not None:
        raw_names = (suite.get("wolfi") or {}).get("finalImages")
        if (
            not isinstance(raw_names, list)
            or not raw_names
            or any(not isinstance(name, str) or not name for name in raw_names)
            or len(set(raw_names)) != len(raw_names)
        ):
            raise SystemExit("ERROR: Scan suite has an invalid final Wolfi image manifest")
        final_names = raw_names
    if final_names:
        images_by_name = {image["name"]: image for image in wolfi["images"]}
        if len(images_by_name) != len(wolfi["images"]):
            raise SystemExit("ERROR: Wolfi reports contain duplicate image names")
        missing = [name for name in final_names if name not in images_by_name]
        if missing:
            raise SystemExit(
                "ERROR: Final Wolfi gate images are absent from reports: "
                + ", ".join(missing)
            )
        selected = [images_by_name[name] for name in final_names]
    else:
        selected = list(wolfi["images"])
    if not selected:
        raise SystemExit("ERROR: Wolfi release gate selected no images")
    occurrences, unique_cves = observed_gate_counts(selected)
    result: dict[str, Any] = {
        "policy": RELEASE_GATE_POLICY,
        "evaluated": False,
        "verified": False,
        "status": "UNVERIFIED",
        "passed": None,
        "reason": "A verified acceptance result was not available.",
        "occurrences": occurrences,
        "uniqueCves": unique_cves,
        "images": [image["name"] for image in selected],
        "acceptanceFile": str(acceptance_path) if acceptance_path is not None else "",
    }

    if acceptance is None:
        result["reason"] = "Wolfi acceptance result is missing from this ad-hoc comparison."
        return result

    if acceptance.get("schemaVersion") != 1:
        raise SystemExit("ERROR: Acceptance result has an unsupported schemaVersion")
    if acceptance.get("policy") != RELEASE_GATE_POLICY:
        raise SystemExit("ERROR: Acceptance result has an unexpected policy")
    evaluated = acceptance.get("evaluated")
    if not isinstance(evaluated, bool):
        raise SystemExit("ERROR: Acceptance result has invalid evaluated state")

    if not evaluated:
        if acceptance.get("passed") is not None:
            raise SystemExit(
                "ERROR: Unevaluated acceptance result must have passed set to null"
            )
        if acceptance.get("images") != []:
            raise SystemExit("ERROR: Unevaluated acceptance result must have no images")
        for label in ("occurrences", "uniqueCves"):
            counts = acceptance.get(label)
            if not isinstance(counts, dict) or any(
                counts.get(severity) is not None for severity in BLOCKING_SEVERITIES
            ):
                raise SystemExit(
                    f"ERROR: Unevaluated acceptance result has invalid {label}"
                )
        reason = acceptance.get("reason")
        if not isinstance(reason, str) or not reason:
            raise SystemExit("ERROR: Unevaluated acceptance result lacks a reason")
        result.update(
            {
                "status": "NOT_EVALUATED",
                "reason": reason,
            }
        )
        return result

    acceptance_passed = acceptance.get("passed")
    if not isinstance(acceptance_passed, bool):
        raise SystemExit(
            "ERROR: Evaluated acceptance result must have a boolean passed value"
        )

    # An acceptance file without the verified suite's final-image manifest, or
    # one paired with an ad-hoc raw scan context, can be displayed but can
    # never establish a release PASS.
    if suite is None or scan_context.get("verified") is not True:
        result.update(
            {
                "evaluated": True,
                "status": "UNVERIFIED",
                "reason": (
                    "Acceptance cannot establish a release result without verified "
                    "raw scan context and the locked final-image manifest."
                ),
                "reportedPassed": acceptance_passed,
            }
        )
        return result

    acceptance_occurrences = gate_count_map(
        acceptance.get("occurrences"), "occurrences"
    )
    acceptance_unique = gate_count_map(acceptance.get("uniqueCves"), "uniqueCves")
    if acceptance_occurrences != occurrences:
        raise SystemExit(
            "ERROR: Acceptance occurrence counts differ from final Wolfi raw reports"
        )
    if acceptance_unique != unique_cves:
        raise SystemExit(
            "ERROR: Acceptance unique-CVE counts differ from final Wolfi raw reports"
        )

    acceptance_images = acceptance.get("images")
    if not isinstance(acceptance_images, list) or len(acceptance_images) != len(selected):
        raise SystemExit(
            "ERROR: Acceptance image manifest differs from final Wolfi raw reports"
        )
    accepted_names: list[str] = []
    for accepted, expected in zip(acceptance_images, selected):
        if not isinstance(accepted, dict):
            raise SystemExit("ERROR: Acceptance result has an invalid image entry")
        image_name = accepted.get("image")
        if not isinstance(image_name, str) or not image_name:
            raise SystemExit("ERROR: Acceptance result has an invalid image name")
        accepted_names.append(image_name)
        report_value = accepted.get("report")
        if not isinstance(report_value, str) or not report_value:
            raise SystemExit("ERROR: Acceptance result has an invalid report path")
        expected_report = Path(expected["report"])
        accepted_report = Path(report_value)
        if accepted_report.name != expected_report.name:
            raise SystemExit(
                "ERROR: Acceptance report manifest differs from final Wolfi raw reports"
            )
        if accepted_report.is_absolute() and accepted_report.exists():
            if accepted_report.resolve() != expected_report.resolve():
                raise SystemExit(
                    "ERROR: Acceptance report path resolves outside the Wolfi raw reports"
                )
        image_occurrences = gate_count_map(
            accepted.get("occurrences"), f"images[{image_name}].occurrences"
        )
        image_unique = gate_count_map(
            accepted.get("uniqueCves"), f"images[{image_name}].uniqueCves"
        )
        expected_occurrences, expected_unique = observed_gate_counts([expected])
        if image_occurrences != expected_occurrences or image_unique != expected_unique:
            raise SystemExit(
                f"ERROR: Acceptance counts differ from raw report for {image_name}"
            )

    if accepted_names != final_names:
        raise SystemExit(
            "ERROR: Acceptance image manifest differs from the scan suite's final images"
        )
    computed_passed = not any(occurrences.values())
    if acceptance_passed != computed_passed:
        raise SystemExit(
            "ERROR: Acceptance passed value differs from final Wolfi raw reports"
        )

    result.update(
        {
            "evaluated": True,
            "verified": True,
            "status": "PASS" if acceptance_passed else "FAIL",
            "passed": acceptance_passed,
            "reason": (
                "Acceptance result matches the verified final Wolfi raw reports."
            ),
        }
    )
    return result


def write_vulnerability_tsv(path: Path, families: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "FAMILY",
                "IMAGE",
                "SEVERITY",
                "OCCURRENCES",
                "UNIQUE_CVES",
                "FIX_AVAILABLE_OCCURRENCES",
                "NO_FIX_OCCURRENCES",
            )
        )
        for family in families:
            scopes = [("ALL", family["counts"])] + [
                (image["name"], image["counts"]) for image in family["images"]
            ]
            for image_name, counts in scopes:
                for severity in (*SEVERITIES, "TOTAL"):
                    writer.writerow(
                        (
                            family["name"],
                            image_name,
                            severity,
                            counts["occurrences"][severity],
                            counts["uniqueCves"][severity],
                            counts["fixAvailability"]["available"]["occurrences"][severity],
                            counts["fixAvailability"]["unavailable"]["occurrences"][severity],
                        )
                    )


def write_native_tool_tsv(path: Path, families: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(("FAMILY", "IMAGE", "NATIVE_TOOL", "SEVERITY", "OCCURRENCES", "UNIQUE_CVES"))
        for family in families:
            scopes = [("ALL", family["nativeTools"])] + [
                (image["name"], image["nativeTools"]) for image in family["images"]
            ]
            for image_name, tools in scopes:
                for tool in tools:
                    for severity in (*SEVERITIES, "TOTAL"):
                        writer.writerow(
                            (
                                family["name"],
                                image_name,
                                tool["nativeTool"],
                                severity,
                                tool["counts"]["occurrences"][severity],
                                tool["counts"]["uniqueCves"][severity],
                            )
                        )


def write_package_contributions_tsv(
    path: Path, families: list[dict[str, Any]]
) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "FAMILY",
                "IMAGE",
                "NATIVE_TOOL",
                "TARGET",
                "PACKAGE_CLASS",
                "PACKAGE_TYPE",
                "PACKAGE_NAME",
                "PACKAGE_PATH",
                "INSTALLED_VERSION",
                "FIXED_VERSION",
                "LAYER_DIGEST",
                "SEVERITY",
                "OCCURRENCES",
                "UNIQUE_CVES",
                "CVE_IDS",
            )
        )
        for family in families:
            for image in family["images"]:
                for package in image["packages"]:
                    for severity in (*SEVERITIES, "TOTAL"):
                        writer.writerow(
                            (
                                family["name"],
                                image["name"],
                                package["nativeTool"],
                                package["target"],
                                package["packageClass"],
                                package["packageType"],
                                package["packageName"],
                                package["packagePath"],
                                package["installedVersion"],
                                package["fixedVersion"],
                                package["layerDigest"],
                                severity,
                                package["counts"]["occurrences"][severity],
                                package["counts"]["uniqueCves"][severity],
                                ",".join(package["vulnerabilityIds"]),
                            )
                        )


def write_vulnerability_layer_tsv(
    path: Path, families: list[dict[str, Any]]
) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "FAMILY",
                "IMAGE",
                "LAYER_DIGEST",
                "SEVERITY",
                "OCCURRENCES",
                "UNIQUE_CVES",
                "CVE_IDS",
            )
        )
        for family in families:
            for image in family["images"]:
                for layer in image["vulnerabilityLayers"]:
                    for severity in (*SEVERITIES, "TOTAL"):
                        writer.writerow(
                            (
                                family["name"],
                                image["name"],
                                layer["layerDigest"],
                                severity,
                                layer["counts"]["occurrences"][severity],
                                layer["counts"]["uniqueCves"][severity],
                                ",".join(layer["vulnerabilityIds"]),
                            )
                        )


def write_remaining_wolfi_tsv(path: Path, wolfi: dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "IMAGE",
                "CVE",
                "SEVERITY",
                "FIX_AVAILABLE",
                "TARGET",
                "PACKAGE_CLASS",
                "PACKAGE_TYPE",
                "PACKAGE_NAME",
                "PACKAGE_PATH",
                "INSTALLED_VERSION",
                "FIXED_VERSION",
                "NATIVE_TOOL",
                "LAYER_DIGEST",
            )
        )
        for image in wolfi["images"]:
            for finding in sorted(
                image["_findings"],
                key=lambda item: (
                    SEVERITIES.index(item["severity"]),
                    item["vulnerabilityId"],
                    item["packageName"],
                ),
                reverse=True,
            ):
                writer.writerow(
                    (
                        image["name"],
                        finding["vulnerabilityId"],
                        finding["severity"],
                        "YES" if finding["fixAvailable"] else "NO",
                        finding["target"],
                        finding["packageClass"],
                        finding["packageType"],
                        finding["packageName"],
                        finding["packagePath"],
                        finding["installedVersion"],
                        finding["fixedVersion"],
                        finding["nativeTool"],
                        finding["layerDigest"],
                    )
                )


def write_image_metrics_tsv(path: Path, families: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "FAMILY",
                "IMAGE",
                "AVAILABLE",
                "SCANNED_IMAGE_ID",
                "CURRENT_IMAGE_ID",
                "PLATFORM",
                "IMAGE_SIZE_BYTES",
                "LAYER_COUNT",
                "LARGEST_HISTORY_LAYER_BYTES",
                "SBOM_COMPONENTS",
                "PACKAGE_MANAGER",
                "INSTALLED_PACKAGE_COUNT",
                "COMPRESSED_SAVE_BYTES",
                "COMPRESSED_EXPORT_BYTES",
                "LIVE_FILESYSTEM_BYTES",
                "ERRORS",
            )
        )
        for family in families:
            for image in family["images"]:
                metrics = image["imageMetrics"]
                writer.writerow(
                    (
                        family["name"],
                        image["name"],
                        str(metrics["available"]).lower(),
                        (image.get("scannedImageIdentity") or {}).get("imageId", ""),
                        metrics["imageId"],
                        metrics["platform"],
                        metrics["imageSizeBytes"],
                        metrics["layerCount"],
                        metrics["largestHistoryLayerBytes"],
                        image["sbomComponents"],
                        metrics["packageManager"],
                        metrics["installedPackageCount"],
                        metrics["compressedSaveBytes"],
                        metrics["compressedExportBytes"],
                        metrics["liveFilesystemBytes"],
                        "; ".join(metrics["errors"]),
                    )
                )


def write_layer_contributions_tsv(path: Path, families: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "FAMILY",
                "IMAGE",
                "HISTORY_INDEX",
                "LAYER_ID",
                "ROOTFS_DIFF_DIGEST",
                "SIZE_BYTES",
                "CREATED_BY",
                "COMMENT",
            )
        )
        for family in families:
            for image in family["images"]:
                for layer in image["imageMetrics"]["historyLayers"]:
                    writer.writerow(
                        (
                            family["name"],
                            image["name"],
                            layer["index"],
                            layer["id"],
                            layer["rootfsDigest"],
                            layer["sizeBytes"],
                            layer["createdBy"],
                            layer["comment"],
                        )
                    )


def write_probe_contributions_tsv(
    path: Path, contributions: list[dict[str, Any]]
) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "NATIVE_TOOL",
                "BASELINE_IMAGE",
                "PROBE_IMAGE",
                "IMAGE_SIZE_DELTA_BYTES",
                "COMPRESSED_SAVE_DELTA_BYTES",
                "COMPRESSED_EXPORT_DELTA_BYTES",
                "LIVE_FILESYSTEM_DELTA_BYTES",
                "PACKAGE_COUNT_DELTA",
                "LAYER_COUNT_DELTA",
                "CRITICAL_DELTA",
                "HIGH_DELTA",
                "MEDIUM_DELTA",
                "LOW_DELTA",
                "UNKNOWN_DELTA",
                "TOTAL_OCCURRENCE_DELTA",
                "TOTAL_UNIQUE_CVE_DELTA",
            )
        )
        for contribution in contributions:
            metrics = contribution["metricDeltas"]
            vulnerabilities = contribution["vulnerabilityDeltas"]
            writer.writerow(
                (
                    contribution["nativeTool"],
                    contribution["baselineImage"],
                    contribution["image"],
                    metrics["imageSizeBytes"],
                    metrics["compressedSaveBytes"],
                    metrics["compressedExportBytes"],
                    metrics["liveFilesystemBytes"],
                    metrics["installedPackageCount"],
                    metrics["layerCount"],
                    vulnerabilities["occurrences"]["CRITICAL"],
                    vulnerabilities["occurrences"]["HIGH"],
                    vulnerabilities["occurrences"]["MEDIUM"],
                    vulnerabilities["occurrences"]["LOW"],
                    vulnerabilities["occurrences"]["UNKNOWN"],
                    vulnerabilities["occurrences"]["TOTAL"],
                    vulnerabilities["uniqueCves"]["TOTAL"],
                )
            )


def write_boundary_comparison_tsv(
    path: Path, comparisons: list[dict[str, Any]]
) -> None:
    with path.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.writer(output_file, delimiter="\t", lineterminator="\n")
        writer.writerow(
            (
                "BOUNDARY",
                "COMPARABLE",
                "UBUNTU_IMAGE",
                "WOLFI_IMAGE",
                "REASON",
                "IMAGE_SIZE_DELTA_BYTES",
                "COMPRESSED_SAVE_DELTA_BYTES",
                "COMPRESSED_EXPORT_DELTA_BYTES",
                "LIVE_FILESYSTEM_DELTA_BYTES",
                "PACKAGE_COUNT_DELTA",
                "CRITICAL_DELTA",
                "HIGH_DELTA",
                "TOTAL_OCCURRENCE_DELTA",
                "TOTAL_UNIQUE_CVE_DELTA",
            )
        )
        for comparison in comparisons:
            metrics = comparison.get("metricDeltasWolfiMinusUbuntu") or {}
            vulnerabilities = comparison.get(
                "vulnerabilityDeltasWolfiMinusUbuntu"
            ) or {"occurrences": {}, "uniqueCves": {}}
            occurrences = vulnerabilities["occurrences"]
            unique = vulnerabilities["uniqueCves"]
            writer.writerow(
                (
                    comparison["boundary"],
                    str(comparison["comparable"]).lower(),
                    comparison["ubuntuImage"],
                    comparison["wolfiImage"],
                    comparison["reason"],
                    metrics.get("imageSizeBytes"),
                    metrics.get("compressedSaveBytes"),
                    metrics.get("compressedExportBytes"),
                    metrics.get("liveFilesystemBytes"),
                    metrics.get("installedPackageCount"),
                    occurrences.get("CRITICAL"),
                    occurrences.get("HIGH"),
                    occurrences.get("TOTAL"),
                    unique.get("TOTAL"),
                )
            )


def display_bytes(value: int | None) -> str:
    return "" if value is None else f"{value / (1024 * 1024):.1f} MiB"


def release_gate_markdown(release_gate: dict[str, Any]) -> str:
    status = release_gate.get("status")
    if status == "PASS":
        return (
            "**Wolfi release gate: PASS** — the evaluated acceptance result "
            "matches the verified final-image reports and contains no Critical "
            "or High findings."
        )
    if status == "FAIL":
        return (
            "**Wolfi release gate: FAIL** — "
            f"{release_gate['occurrences']['CRITICAL']} Critical and "
            f"{release_gate['occurrences']['HIGH']} High occurrences."
        )
    label = "NOT EVALUATED" if status == "NOT_EVALUATED" else "UNVERIFIED"
    return f"**Wolfi release gate: {label}** — {release_gate.get('reason', '')}"


def write_markdown(
    path: Path,
    families: list[dict[str, Any]],
    full: bool,
    scan_context: dict[str, Any],
    boundaries: list[dict[str, Any]],
    probes: list[dict[str, Any]],
    native_tool_versions: dict[str, Any] | None,
    release_gate: dict[str, Any],
) -> None:
    lines = [
        "# Ubuntu and Wolfi image comparison",
        "",
        "## Comparison validity",
        "",
        (
            "**Verified:** Ubuntu and Wolfi raw reports use the same Trivy "
            "version, database snapshot, platform, and scanner options."
            if scan_context.get("verified")
            else f"**Unverified ad-hoc comparison:** {scan_context.get('reason', '')}"
        ),
        release_gate_markdown(release_gate),
        "",
        "The Ubuntu header-package ignore result is a separate policy-adjusted family; it is not used as the raw baseline.",
        (
            "The opaque, unexpanded VSIX transfer archive was excluded from both raw families."
            if scan_context.get("vsixArchiveExcluded")
            else "The VSIX transfer archive was included in this scan."
        ),
        (
            f"**mongosh package/runtime discrepancy:** APK `{native_tool_versions.get('apkVersion')}` reports runtime `{native_tool_versions.get('runtimeVersion')}`; the native package is retained intentionally."
            if native_tool_versions
            and native_tool_versions.get("packageRuntimeVersionDiscrepancy") is True
            else "mongosh package/runtime versions agree."
            if native_tool_versions and native_tool_versions.get("enabled") is True
            else "mongosh package/runtime test report was not available to this comparison."
        ),
        "",
        "## Equivalent boundaries",
        "",
        "| Boundary | Comparable | Ubuntu | Wolfi | Reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for comparison in boundaries:
        lines.append(
            f"| {comparison['boundary']} | "
            f"{'yes' if comparison['comparable'] else '**no**'} | "
            f"`{comparison['ubuntuImage']}` | `{comparison['wolfiImage']}` | "
            f"{comparison['reason']} |"
        )
    lines.extend(
        [
        "",
        "## Vulnerabilities",
        "",
        "| Family | Image | Critical | High | Medium | Low | Unknown | Total | Unique CVEs | Fixable |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    for family in families:
        scopes = [("ALL", family["counts"])] + [
            (image["name"], image["counts"]) for image in family["images"]
        ]
        for image_name, counts in scopes:
            occurrences = counts["occurrences"]
            lines.append(
                f"| {family['name']} | `{image_name}` | {occurrences['CRITICAL']} | "
                f"{occurrences['HIGH']} | {occurrences['MEDIUM']} | {occurrences['LOW']} | "
                f"{occurrences['UNKNOWN']} | {occurrences['TOTAL']} | "
                f"{counts['uniqueCves']['TOTAL']} | "
                f"{counts['fixAvailability']['available']['occurrences']['TOTAL']} |"
            )
    lines.extend(
        (
            "",
            "## Image metrics",
            "",
            "| Family | Image | Docker size | Layers | Packages | SBOM components | Compressed save | Compressed export | Live filesystem |",
            "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        )
    )
    for family in families:
        for image in family["images"]:
            metrics = image["imageMetrics"]
            lines.append(
                f"| {family['name']} | `{image['name']}` | "
                f"{display_bytes(metrics['imageSizeBytes'])} | "
                f"{metrics['layerCount'] if metrics['layerCount'] is not None else ''} | "
                f"{metrics['installedPackageCount'] if metrics['installedPackageCount'] is not None else ''} | "
                f"{image['sbomComponents'] if image['sbomComponents'] is not None else ''} | "
                f"{display_bytes(metrics['compressedSaveBytes'])} | "
                f"{display_bytes(metrics['compressedExportBytes'])} | "
                f"{display_bytes(metrics['liveFilesystemBytes'])} |"
            )
    lines.extend(
        (
            "",
            "## Native-tool probes",
            "",
            "| Tool/profile | Size delta | Package delta | Critical delta | High delta | Total CVE occurrence delta |",
            "| --- | ---: | ---: | ---: | ---: | ---: |",
        )
    )
    if probes:
        for contribution in probes:
            metrics = contribution["metricDeltas"]
            vulnerabilities = contribution["vulnerabilityDeltas"]["occurrences"]
            lines.append(
                f"| {contribution['nativeTool']} | "
                f"{display_bytes(metrics['imageSizeBytes'])} | "
                f"{metrics['installedPackageCount'] if metrics['installedPackageCount'] is not None else ''} | "
                f"{vulnerabilities['CRITICAL']} | {vulnerabilities['HIGH']} | "
                f"{vulnerabilities['TOTAL']} |"
            )
    else:
        lines.append(
            "| unavailable |  |  |  |  | Probe images were not present in this scan. |"
        )
    lines.extend(
        (
            "",
            "Occurrence totals count every affected package instance; unique CVEs are deduplicated by vulnerability ID.",
            "Compressed save/export and live-filesystem measurements are included only when `--full-image-metrics` is used."
            if not full
            else "Live-filesystem size is the sum of regular-file logical sizes in `docker export`; compressed-export and compressed-save sizes are gzip streams produced from `docker export` and `docker image save` respectively.",
            "Every remaining Wolfi finding, including fixed-version data, is listed in `remaining-wolfi-findings.tsv`.",
            "",
        )
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def strip_internal_values(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: strip_internal_values(item)
            for key, item in value.items()
            if not key.startswith("_")
        }
    if isinstance(value, list):
        return [strip_internal_values(item) for item in value]
    return value


def unavailable_metrics(reason: str) -> dict[str, Any]:
    return {
        "available": False,
        "imageId": "",
        "platform": "",
        "imageSizeBytes": None,
        "layerCount": None,
        "rootfsLayerDigests": [],
        "largestHistoryLayerBytes": None,
        "historyLayers": [],
        "packageManager": "",
        "installedPackageCount": None,
        "compressedSaveBytes": None,
        "compressedExportBytes": None,
        "liveFilesystemBytes": None,
        "errors": [reason],
    }


def main() -> None:
    args = parse_args()
    if args.skip_image_metrics and args.full_image_metrics:
        raise SystemExit("ERROR: --skip-image-metrics and --full-image-metrics conflict")
    if args.skip_image_metrics and args.require_image_metrics:
        raise SystemExit("ERROR: --skip-image-metrics and --require-image-metrics conflict")

    # A newly requested evaluation makes any previous PASS non-current before
    # report validation or the potentially long full-image metric collection.
    # Preserve it beside the canonical path for manual recovery if this run
    # fails or is interrupted; only a complete new generation becomes current.
    previous_output_dir = quarantine_current_output_directory(args.output_dir)

    lock_identity: dict[str, Any] | None = None
    if args.wolfi_lock is not None:
        lock_identity = load_wolfi_lock_identity(args.wolfi_lock)
    elif not args.allow_unverified_scan_context:
        raise SystemExit(
            "ERROR: --wolfi-lock is required for a verified release comparison"
        )

    ubuntu = load_family("ubuntu-raw", args.ubuntu_dir.resolve())
    wolfi = load_family("wolfi-raw", args.wolfi_dir.resolve())
    policy = (
        load_family("ubuntu-policy-header-packages", args.ubuntu_policy_dir.resolve())
        if args.ubuntu_policy_dir is not None
        else None
    )
    scan_context = verify_scan_context(
        ubuntu["scanMetadata"],
        wolfi["scanMetadata"],
        policy["scanMetadata"] if policy is not None else None,
        args.allow_unverified_scan_context,
    )
    if lock_identity is None:
        scan_context["verified"] = False
        scan_context["reason"] = (
            "No current Wolfi lock was supplied; report and final-image identity "
            "cannot be verified."
        )

    suite: dict[str, Any] | None = None
    if args.suite_metadata is not None:
        if not args.suite_metadata.is_file():
            if not args.allow_unverified_scan_context:
                raise SystemExit(
                    f"ERROR: Scan-suite provenance not found: {args.suite_metadata}"
                )
        else:
            suite = read_json(args.suite_metadata.resolve())
            if suite.get("scannerContextFrozen") is not True:
                raise SystemExit("ERROR: Scan suite does not claim a frozen context")
            if suite.get("platform") != scan_context.get("scannerOptions", {}).get(
                "platform"
            ):
                raise SystemExit("ERROR: Scan-suite platform differs from raw metadata")
            suite_trivy = suite.get("trivy") or {}
            raw_trivy = (ubuntu["scanMetadata"] or {}).get("trivy") or {}
            if suite_trivy.get("Version") != raw_trivy.get("Version"):
                raise SystemExit("ERROR: Scan-suite Trivy version differs from raw metadata")
            for database_key in ("VulnerabilityDB", "JavaDB"):
                suite_database = suite_trivy.get(database_key) or {}
                raw_database = raw_trivy.get(database_key) or {}
                if (
                    suite_database.get("Version") != raw_database.get("Version")
                    or suite_database.get("UpdatedAt") != raw_database.get("UpdatedAt")
                ):
                    raise SystemExit(
                        f"ERROR: Scan-suite {database_key} snapshot differs from raw metadata"
                    )
            expected_ubuntu_images = ((suite.get("ubuntu") or {}).get("images")) or []
            expected_wolfi_images = ((suite.get("wolfi") or {}).get("images")) or []
            actual_ubuntu_images = (ubuntu["scanMetadata"] or {}).get("images") or []
            actual_wolfi_images = (wolfi["scanMetadata"] or {}).get("images") or []
            if expected_ubuntu_images != actual_ubuntu_images:
                raise SystemExit("ERROR: Scan-suite Ubuntu image manifest differs")
            if expected_wolfi_images != actual_wolfi_images:
                raise SystemExit("ERROR: Scan-suite Wolfi image manifest differs")
            wolfi_suite = suite.get("wolfi")
            ubuntu_suite = suite.get("ubuntu")
            if not isinstance(wolfi_suite, dict) or not isinstance(ubuntu_suite, dict):
                raise SystemExit("ERROR: Scan suite has invalid family metadata")
            if lock_identity is not None:
                if wolfi_suite.get("lockSha256") != lock_identity["sha256"]:
                    raise SystemExit(
                        "ERROR: Scan suite was not produced from the current exact "
                        "Wolfi lock bytes"
                    )
                if suite.get("platform") != lock_identity["platform"]:
                    raise SystemExit(
                        "ERROR: Scan-suite platform differs from the current Wolfi lock"
                    )
            if ubuntu_suite.get("enabled") is not True:
                raise SystemExit("ERROR: Scan suite does not contain an Ubuntu baseline")
            if wolfi_suite.get("ignorePolicyApplied") is not False:
                raise SystemExit("ERROR: Scan suite does not describe raw Wolfi findings")
            final_images = wolfi_suite.get("finalImages")
            if (
                not isinstance(final_images, list)
                or len(final_images) != 3
                or any(image not in expected_wolfi_images for image in final_images)
                or len(set(final_images)) != len(final_images)
            ):
                raise SystemExit("ERROR: Scan-suite final Wolfi image manifest is invalid")
            if lock_identity is not None and final_images != lock_identity["finalImages"]:
                raise SystemExit(
                    "ERROR: Scan-suite final Wolfi image manifest differs from the "
                    "current lock"
                )
            wolfi_boundaries = wolfi_suite.get("boundaries")
            if not isinstance(wolfi_boundaries, dict) or [
                wolfi_boundaries.get(key) for key in ("dod", "vscode", "toolchain")
            ] != final_images:
                raise SystemExit("ERROR: Scan-suite Wolfi boundaries are invalid")
            native_tool_probe_assessment_complete = (
                validate_native_tool_probe_assessment(
                    wolfi_suite, expected_wolfi_images, lock_identity
                )
            )
            ubuntu_boundaries = ubuntu_suite.get("boundaries")
            if not isinstance(ubuntu_boundaries, dict) or any(
                ubuntu_boundaries.get(key) not in expected_ubuntu_images
                for key in ("dod", "vscode")
            ):
                raise SystemExit("ERROR: Scan-suite Ubuntu boundaries are invalid")
            all_tools = ubuntu_suite.get("allToolsComparison")
            if not isinstance(all_tools, dict):
                raise SystemExit("ERROR: Scan suite lacks all-tools comparison metadata")
            if all_tools.get("equivalent") is True:
                comparator_provenance = all_tools.get("provenance")
                if (
                    not native_tool_probe_assessment_complete
                    or all_tools.get("status") != "included"
                    or all_tools.get("image") not in expected_ubuntu_images
                    or not isinstance(comparator_provenance, dict)
                    or comparator_provenance.get("validated") is not True
                    or comparator_provenance.get("scanIdentityValidated") is not True
                ):
                    raise SystemExit(
                        "ERROR: Scan-suite all-tools equivalence is not substantiated"
                    )
            include_vsix = suite.get("includeVsixArchive")
            if not isinstance(include_vsix, bool):
                raise SystemExit("ERROR: Scan suite has an invalid VSIX inclusion setting")
            raw_skip_files = scan_context.get("scannerOptions", {}).get("skipFiles") or []
            vsix_was_excluded = (
                "/home/vscode/vscode-extensions.tar.gz" in raw_skip_files
            )
            if include_vsix == vsix_was_excluded:
                raise SystemExit(
                    "ERROR: Scan-suite VSIX setting differs from raw scanner options"
                )
    elif not args.allow_unverified_scan_context:
        raise SystemExit(
            "ERROR: --suite-metadata is required for an equivalence comparison"
        )

    acceptance_path = (
        args.acceptance_file.resolve() if args.acceptance_file is not None else None
    )
    acceptance: dict[str, Any] | None = None
    if acceptance_path is None:
        if not args.allow_unverified_scan_context:
            raise SystemExit(
                "ERROR: --acceptance-file is required for a release comparison"
            )
    elif acceptance_path.is_file():
        acceptance = read_json(acceptance_path)
    elif not args.allow_unverified_scan_context:
        raise SystemExit(f"ERROR: Wolfi acceptance result not found: {acceptance_path}")
    release_gate = build_release_gate(
        wolfi, suite, scan_context, acceptance, acceptance_path
    )

    native_tool_versions = None
    if args.native_tool_version_report is not None:
        if args.native_tool_version_report.is_file():
            native_tool_versions = read_json(args.native_tool_version_report.resolve())
            if native_tool_versions.get("nativeTool") != "mongosh":
                raise SystemExit("ERROR: Native-tool version report is not for mongosh")
            enabled = native_tool_versions.get("enabled")
            discrepancy = native_tool_versions.get(
                "packageRuntimeVersionDiscrepancy"
            )
            if not isinstance(enabled, bool) or not isinstance(discrepancy, bool):
                raise SystemExit("ERROR: Native-tool version report has invalid booleans")
            if enabled and (
                not isinstance(native_tool_versions.get("apkVersion"), str)
                or not native_tool_versions.get("apkVersion")
                or not isinstance(native_tool_versions.get("runtimeVersion"), str)
                or not native_tool_versions.get("runtimeVersion")
            ):
                raise SystemExit("ERROR: Native-tool version report lacks versions")
            if suite is not None:
                expected_toolchain = str(
                    (((suite.get("wolfi") or {}).get("boundaries") or {}).get("toolchain"))
                    or ""
                )
                if native_tool_versions.get("image") != expected_toolchain:
                    raise SystemExit(
                        "ERROR: Native-tool version report is for a different image"
                    )
        elif not args.allow_unverified_scan_context:
            raise SystemExit(
                "ERROR: Native-tool version report not found: "
                f"{args.native_tool_version_report}"
            )

    families = [ubuntu, wolfi] + ([policy] if policy is not None else [])
    docker_available = shutil.which("docker") is not None
    metric_cache: dict[str, dict[str, Any]] = {}
    for family in families:
        for image in family["images"]:
            if args.skip_image_metrics:
                metrics = unavailable_metrics("image metrics skipped")
            elif not docker_available:
                metrics = unavailable_metrics("docker command not found")
            elif image["name"] in metric_cache:
                metrics = metric_cache[image["name"]]
            else:
                metrics = collect_image_metrics(image["name"], args.full_image_metrics)
                metric_cache[image["name"]] = metrics
            image["imageMetrics"] = metrics
            scanned_identity = image.get("scannedImageIdentity") or {}
            if metrics["available"] and scanned_identity:
                if metrics["imageId"] != scanned_identity.get("imageId"):
                    raise SystemExit(
                        f"ERROR: Docker tag changed since scan: {image['name']}"
                    )
                if metrics["platform"] != scanned_identity.get("platform"):
                    raise SystemExit(
                        f"ERROR: Docker image platform changed since scan: {image['name']}"
                    )
            if args.require_image_metrics:
                required_metrics = [
                    "imageSizeBytes",
                    "layerCount",
                    "installedPackageCount",
                ]
                if args.full_image_metrics:
                    required_metrics.extend(
                        (
                            "compressedSaveBytes",
                            "compressedExportBytes",
                            "liveFilesystemBytes",
                        )
                    )
                missing_metrics = [
                    key for key in required_metrics if metrics.get(key) is None
                ]
                if not metrics["available"] or missing_metrics or metrics["errors"]:
                    errors = "; ".join(metrics["errors"])
                    detail = ", ".join(missing_metrics) or "image inspection"
                    if metrics["errors"] and not missing_metrics:
                        detail = "one or more metric collectors"
                    raise SystemExit(
                        f"ERROR: Required Docker metrics unavailable for "
                        f"{image['name']} ({detail}): {errors}"
                    )

    probe_contributions = build_probe_contributions(wolfi, suite)
    boundary_comparisons = build_boundary_comparisons(ubuntu, wolfi, suite)

    generated_at = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )
    output = {
        "schemaVersion": 2,
        "generatedAt": generated_at,
        "fullImageMetrics": args.full_image_metrics,
        "scanContext": scan_context,
        "scanSuite": suite,
        "boundaryComparisons": boundary_comparisons,
        "probeContributions": probe_contributions,
        "releaseGate": release_gate,
        "nativeToolVersions": native_tool_versions,
        "families": strip_internal_values(families),
    }

    def write_output_set(staging_dir: Path) -> None:
        (staging_dir / "comparison.json").write_text(
            json.dumps(output, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        write_vulnerability_tsv(
            staging_dir / "vulnerability-comparison.tsv", families
        )
        write_native_tool_tsv(
            staging_dir / "native-tool-contributions.tsv", families
        )
        write_package_contributions_tsv(
            staging_dir / "package-contributions.tsv", families
        )
        write_vulnerability_layer_tsv(
            staging_dir / "vulnerability-layer-contributions.tsv", families
        )
        write_remaining_wolfi_tsv(
            staging_dir / "remaining-wolfi-findings.tsv", wolfi
        )
        write_image_metrics_tsv(staging_dir / "image-metrics.tsv", families)
        write_layer_contributions_tsv(
            staging_dir / "image-layer-contributions.tsv", families
        )
        write_probe_contributions_tsv(
            staging_dir / "native-tool-probe-contributions.tsv", probe_contributions
        )
        write_boundary_comparison_tsv(
            staging_dir / "equivalent-boundary-comparison.tsv", boundary_comparisons
        )
        write_markdown(
            staging_dir / "comparison.md",
            families,
            args.full_image_metrics,
            scan_context,
            boundary_comparisons,
            probe_contributions,
            native_tool_versions,
            release_gate,
        )

    publish_complete_output_directory(
        args.output_dir, write_output_set, previous_output_dir
    )
    print(f"Wolfi/Ubuntu comparison written to {args.output_dir}")


if __name__ == "__main__":
    main()
